baseURL: "/"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
buildFuture: true
disableKinds:
  - "RSS"
  - "taxonomyTerm"
googleAnalytics: ""
languageCode: "pt-br"
title: "72Horas"
metaDataFormat: "yaml"

ignoreErrors:
  - "error-remote-getjson"
