baseURL: "/"
defaultContentLanguage: "pt"
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
buildFuture: true
disableKinds:
  - "RSS"
  - "taxonomy"
locale: "pt-br"
title: "72Horas"

services:
  googleAnalytics:
    id: ""
