header:
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "https://plataforma-72horas.medium.com/sobre-os-dados-do-72-horas-ae929bd460e6"
  weight: 1
- identifier: "report"
  name: "Relatório"
  url: "https://issuu.com/72horas.org/docs/relatorio_72horas.org__eleic_a_o2020"
  weight: 2
- identifier: "donate"
  name: "Quem somos"
  url: "https://plataforma-72horas.medium.com/72-horas-quem-somos-69cb31f79da9"
  weight: 3
footer:
- identifier: "report"
  name: "Relatório"
  url: "https://issuu.com/72horas.org/docs/relatorio_72horas.org__eleic_a_o2020"
  weight: 1
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "https://plataforma-72horas.medium.com/sobre-os-dados-do-72-horas-ae929bd460e6"
  weight: 2
- identifier: "press"
  name: "Imprensa"
  url: "https://plataforma-72horas.medium.com/tudo-que-publicaram-da-plataforma-72-horas-na-imprensa-90613983b23c"
  weight: 3
- identifier: "donate"
  name: "Quem somos"
  url: "https://plataforma-72horas.medium.com/72-horas-quem-somos-69cb31f79da9"
  weight: 4
- identifier: "runs2020"
  name: "Eleição de 2020"
  url: "https://2020.72horas.org/"
  parent: "previousRuns"
- identifier: "previousRuns"
  name: "Eleições anteriores"
  weight: 5
