header:
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "/sobre-os-dados/"
  weight: 1
- identifier: "report"
  name: "Relatório"
  url: "https://issuu.com/72horas.org/docs/relatorio_72horas.org__eleic_a_o2020"
  weight: 2
- identifier: "donate"
  name: "Quem somos"
  url: "/quem-somos/"
  weight: 3
footer:
- identifier: "report"
  name: "Relatório"
  url: "https://issuu.com/72horas.org/docs/relatorio_72horas.org__eleic_a_o2020"
  weight: 1
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "/sobre-os-dados/"
  weight: 2
- identifier: "press"
  name: "Imprensa"
  url: "/imprensa/"
  weight: 3
- identifier: "donate"
  name: "Quem somos"
  url: "/quem-somos/"
  weight: 4
- identifier: "runs2020"
  name: "Eleição de 2020"
  url: "https://2020.72horas.org/"
  parent: "previousRuns"
- identifier: "runs2022"
  name: "Eleição de 2022"
  url: "https://2022.72horas.org/"
  parent: "previousRuns"
- identifier: "previousRuns"
  name: "Eleições anteriores"
  weight: 5
