header:
- identifier: "home"
  name: "Página inicial"
  url: "/"
  weight: 1
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "/sobre-os-dados/"
  weight: 2
- identifier: "whoWeAre"
  name: "Quem somos"
  url: "/quem-somos/"
  weight: 3
footer:
- identifier: "home"
  name: "Página inicial"
  url: "/"
  weight: 1
- identifier: "aboutData"
  name: "Sobre os dados"
  url: "/sobre-os-dados/"
  weight: 2
- identifier: "press"
  name: "Imprensa"
  url: "/imprensa/"
  weight: 3
- identifier: "whoWeAre"
  name: "Quem somos"
  url: "/quem-somos/"
  weight: 4
