enableInlineShortcodes: false
exec:
  allow:
    - "^dart-sass-embedded$"
    - "^dart-sass$"
    - "^go$"
    - "^node$"
    - "^npx$"
    - "^postcss$"
    - "babel"
    - "git"
  osEnv:
    - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"
funcs:
  getenv:
    - "NODE_ENV"
    - "^HUGO_"
  http:
    methods:
      - "(?i)GET|POST"
    urls:
      - ".*"
