enableInlineShortcodes: false
exec:
  allow:
    - '^dart-sass-embedded$'
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - 'babel'
  osEnv:
    - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
funcs:
  getenv:
    - "NODE_ENV"
  http:
    methods:
      - '(?i)GET|POST'
    urls:
      - '.*'
