baseURL: "/"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
buildFuture: true
disableKinds:
  - "RSS"
  - "taxonomyTerm"
googleAnalytics: ""
languageCode: "pt-br"
title: "72Horas"
menu:
  header:
  # - identifier: "aboutUs"
  #   name: "Quem Somos"
  #   url: "/"
  #   weight: 1
  - identifier: "donate"
    name: "Doe"
    url: "https://www.catarse.me/72horas?ref=project_link"
    weight: 2
metaDataFormat: "yaml"
params:
  name: "72Horas"
  siteDescription: "A Plataforma 72 horas acompanha em tempo real e entrega de forma simples os repasses dos fundos. Filtro por estado, município, partido, gênero e etnia. Fique por dentro a respeito do uso do dinheiro público nas Eleições 2020."
  contactEmail: "plataforma.72horas@gmail.com"
  tagline: ""
  shareImages:
    default: "assets/images/default.jpg"
    twitter: "assets/images/twitter.jpg"
    facebook: "assets/images/facebook.jpg"
