baseURL: "/"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
buildFuture: true
disableKinds:
  - "RSS"
  - "taxonomyTerm"
googleAnalytics: ""
languageCode: "pt-br"
title: "72Horas"
menu:
  header:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
metaDataFormat: "yaml"
params:
  name: "72Horas"
  siteDescription: ""
  contactEmail: "plataforma.72horas@gmail.com"
  tagline: ""
  shareImages:
    default: "assets/images/default.jpg"
    twitter: "assets/images/twitter.jpg"
    facebook: "assets/images/facebook.jpg"
