[build]
  publish = "public"
  command = "hugo version && npm install && npm run build"

[build.environment]
  HUGO_VERSION = "0.101.0"

[context.dev.environment]
  HUGO_ENVIRONMENT = "staging"

# Temporally until TSE add us back to permitted list
[context.production.environment]
  HUGO_ENVIRONMENT = "staging"
