[build]
  publish = "public"
  command = "curl -sfLO \"https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && mkdir -p \"${HOME}/.local\" && tar -C \"${HOME}/.local\" -xf \"dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && rm \"dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && export PATH=\"${HOME}/.local/dart-sass:${PATH}\" && hugo version && npm install && npm run build"

[build.environment]
  HUGO_VERSION = "0.164.0"
  DART_SASS_VERSION = "1.101.0"
  NODE_VERSION = "24.18.0"

[context.dev.environment]
  HUGO_ENVIRONMENT = "staging"
