backend:
  name: git-gateway
  repo: AppCivico/72h-www # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  -
    label: "Parceiros e Organizações"
    name: "partners"
    folder: "content/partners"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Titulo"
        name: "title"
        widget: "string"
        tagname: "h1"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Imagem (400 X 300)"
        name: "Image"
        widget: "image"
      -
        label: "Ordem"
        name: "weight"
        widget: "number"
      -
        label: "Rascunho"
        name: "draft"
        widget: "boolean"
        default: true
